// 团队允许加入的类型
export const GROUP_ALLOW_APPLY_TYPE = {
  NONE: 1,
  ALL: 2,
};
// 所有团体类型公用的权限
export const GROUP_PERMISSION = {
  ACCESS: 'ACCESS',
  DELETE: 'DELETE',
  CHANGE: 'CHANGE',
  CREATE_ROLE: 'CREATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  CHECK_USER: 'CHECK_USER',
  INVITE_USER: 'INVITE_USER',
  DELETE_USER: 'DELETE_USER',
  CHANGE_USER_ROLE: 'CHANGE_USER_ROLE',
  CHANGE_USER_REMARK: 'CHANGE_USER_REMARK',
} as const;
// 申请加入如何检查
export const APPLICATION_CHECK_TYPE = {
  NO_NEED_CHECK: 1,
  ADMIN_CHECK: 2,
};
