import { GROUP_ALLOW_APPLY_TYPE, GROUP_PERMISSION } from './group';

// 团队允许加入的类型
export const TEAM_ALLOW_APPLY_TYPE = {
  ...GROUP_ALLOW_APPLY_TYPE,
};
// 团队权限
export const TEAM_PERMISSION = {
  ...GROUP_PERMISSION,
  CREATE_TERM_BANK: 'CREATE_TERM_BANK',
  ACCESS_TERM_BANK: 'ACCESS_TERM_BANK',
  CHANGE_TERM_BANK: 'CHANGE_TERM_BANK',
  DELETE_TERM_BANK: 'DELETE_TERM_BANK',
  CREATE_TERM: 'CREATE_TERM',
  CHANGE_TERM: 'CHANGE_TERM',
  DELETE_TERM: 'DELETE_TERM',
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_SET: 'CREATE_PROJECT_SET',
  CHANGE_PROJECT_SET: 'CHANGE_PROJECT_SET',
  DELETE_PROJECT_SET: 'DELETE_PROJECT_SET',
  USE_OCR_QUOTA: 'USE_OCR_QUOTA',
  USE_MT_QUOTA: 'USE_MT_QUOTA',
  INSIGHT: 'INSIGHT',
} as const;
